### ISSUE TITLE
Allow pyre to read configuration from `pyproject.toml`

### ISSUE THREAD

**Issue by xshapira** [vthemelis/pyre-lsp#1]
Thanks for the effort to make this extension happen!

If pyre can use the `pyproject.toml` file for its settings like most tools do, that would be awesome.

This might help:
https://github.com/facebook/pyre-check/pull/799

**Comment by vthemelis** [comment]
Hello! I think that this is one for the core pyre library (as this is what is reading all the config). Should I delegate this to https://github.com/facebook/pyre-check/issues/695 ?

**Comment by xshapira** [comment]
@vthemelis Yes, you should. That request was created two years ago.

The Pyre team has gone radio silent on us.

**Comment by vthemelis** [comment]
Thanks! Will close this in favour of the original pyre-check issue. I can see how this sort of thing may not be at the top of their priorities.

FWIW I find that using pyproject.toml for everything can get a bit unergonomoc so I opt in for separate config files when I can. :)
